### ISSUE TITLE
Hardware configuration

### ISSUE THREAD

**Issue by SargamMenghani** [BShakhovsky/PolyphonicPianoTranscription#1]
Hello,

First of all, thank you so much for these notebooks and the explanation of onsets_and_frames model! It has been very helpful

We are trying to train magenta's onsets_and_frames model for our dataset, which is a slight modification to maestro (we are training using magenta's repo). Our training seems to be too slow. It takes almost 48 hours to train 50k steps. We are using a batch size of 8 with truncated_length_secs parameter set to 20. The other parameters are set to default. The size of the training dataset is the same as what we get with maestro dataset (around 27000 records). We are using a 12 gb Titan XP gpu for training.

When we looked through your `Training, Validation, Testing` notebook, your training time seemed much faster than us (around 4 hours for nearly 700k steps). Do you mind telling us the hardware configuration you had used?

Thank you in advance!

**Comment by BShakhovsky** [comment]
Hello Sargam,
 
My gpu is GeForce GTX 1050 Ti, and yours seems to be newer and faster.
 
There could be confusion in numbers for our training speeds due to the following three reasons:
1. I split the model into separate submodels (onsets, offsets, frames (actives)) and trained them separately. So, whenever you see how much time it took to train one submodel, you should multiply it by 3 (or by 4 if you also take into account volumes/velocities submodel).
2. The word "step" could be misleading. In my case "step" means one musical record of 20 seconds. But there are several records per batch size (8 in your case, I used batch size of 4).
3. You say that it took me 4 hours for nearly 700k steps. Does this mean, 4 * 60 * 60 / 700 =~ 20 milliseconds per step? This is probably evaluation speed. Training speed of one submodel is actually around 80 ms/step.
 
So, it takes you almost 48 hours to train 50k steps. By step, do you mean one musical record or one batch of 8 records? If former, then it is one epoch (27K records) per day - then yes, it is too slow. If latter, then it is several hours per epoch - then it is not so bad, my training speed is close.
